config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  post 'reservations/set_dates_and_redirect'
  post 'reservations/set_dates_room_types'
  post 'reservations/set_dates'
  get 'dashboard/hostels'
  get 'dashboard/reservations'
  get 'dashboard/hostel/:id/tenants', to: 'dashboard#tenants',
                                                   as: 'dashboard_tenants'
  root 'pages#index'
  get 'reservations/:id/pre_pay', to: 'reservations#pre_pay', as: 'reservation_pre_pay'
  get 'reservations/:id/execute', to: 'reservations#execute', as: 'reservation_execute'
  resources :reservations, only: [:index, :show, :destroy]
  resources :reserved_rooms, only: [:update, :destroy] do
    resources :reservations, only: [:update]
  end
  resources :hostels do
    resources :comments, only: [:create]
    resources :hostel_features, only: [:index, :edit, :create, :update, :destroy]
    resources :room_types, only: [:index, :new, :edit, :create, :update, :destroy] do
      post 'reservations/create'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  ## API ##
  get 'api/region/:id', to: 'api#region'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true

  belongs_to :hostel_registration
  has_one :hostel, through: :hostel_registration
  has_one :user, through: :hostel_registration
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :hostels
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :address_number, presence: true, numericality: { only_integer: true }
  validates :principal_image, presence: true

  belongs_to :commune

  has_many :hostel_registrations, dependent: :destroy
  has_many :users, through: :hostel_registrations
  has_many :comments, through: :hostel_registrations
  has_many :hostel_features, dependent: :destroy
  has_many :room_types, dependent: :destroy

  has_one :region, through: :commune
  has_one_attached :principal_image

  def region_id
    if defined? region.id
      region.id
    else
      nil
    end
  end

  def full_address
    "Chile, #{region.full_name}, #{commune.full_name}, #{address} #{address_number}"
  end

  def value_per_night_from
    room_types.map { |e| e.value_per_night }.min.to_i
  end

  def rooms_left_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    room_types.map { |r| r.rooms_left_in_range(starting_date:starting_date, ending_date:ending_date) }.sum
  end

end

app/models/hostel_feature.rb
class HostelFeature < ApplicationRecord
  validates :title, presence: true
  belongs_to :hostel

  has_one_attached :image
end

app/models/hostel_registration.rb
class HostelRegistration < ApplicationRecord
  belongs_to :user
  belongs_to :hostel
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy

  enum role: %i[user admin]

  def pending_reservations
    reservations.where(payed: false)
  end

  def has_active_reservations?
    reservations.select { |r| r.payed? && r.in_date? }.count.positive?
  end

  def no_expired_reservations?
    reservations.select { |r| r.payed? && !r.expired? }.count.positive?
  end
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :communes
  has_many :hostels, through: :communes
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hostel_registration
  has_one :user, through: :hostel_registration
  has_one :hostel, through: :hostel_registration
  has_many :reserved_rooms, dependent: :destroy
  has_many :room_types, through: :reserved_rooms

  def actual_total
    total_counter = 0
    reserved_rooms.each { |r| total_counter += r.total }
    total_counter
  end

  def f_starting_date
    starting_date.strftime('%d/%m/%Y')
  end

  def f_ending_date
    ending_date.strftime('%d/%m/%Y')
  end

  def days
    (ending_date - starting_date).to_i
  end

  def days_left
    (ending_date - Date.current).to_i
  end

  def days_remaining
    (starting_date - Date.current).to_i
  end

  def date_hash
    {starting_date: starting_date, ending_date: ending_date}
  end

  def started?(date: Date.current)
    date >= starting_date
  end

  def expired?(date: Date.current)
    date > ending_date
  end

  def in_date?(date: Date.current)
    started?(date: date) && !expired?(date: date)
  end
end

app/models/reserved_room.rb
class ReservedRoom < ApplicationRecord
  belongs_to :reservation
  belongs_to :room_type

  def total
    room_type.value_per_night * quantity
  end
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  validates :name, presence: true
  validates :number_rooms, presence: true, numericality: { only_integer: true }
  validates :value_per_night, presence: true, numericality: { only_integer: true }

  belongs_to :hostel
  has_many :reserved_rooms

  has_one_attached :image

  def occupied_rooms(date: Date.current)
    reserved_rooms.map { |r| r.reservation.in_date?(date: date) ? (r.reservation.payed ? r.quantity : 0) : 0 }.sum
  end

  def occupied_rooms_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    date_counter = starting_date
    rooms_stack = []
    while date_counter <= ending_date
      rooms_stack += [occupied_rooms(date: date_counter)]
      date_counter += 1
    end
    rooms_stack.max
  end

  def rooms_left(date: Date.current)
    number_rooms - occupied_rooms(date:date)
  end

  def rooms_left_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    number_rooms - occupied_rooms_in_range(starting_date:starting_date, ending_date:ending_date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hostel_registrations
  has_many :hostels, through: :hostel_registrations
  has_many :reservations, through: :hostel_registrations

  def full_name
    "#{first_name} #{middle_name} #{first_surname} #{second_surname}"
  end

  enum gender: %i[male female other]
  enum access_level: %i[user admin]
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def region
    @region = Region.find(params[:id])
    @json = {
      region: @region,
      communes: @region.communes
    }

    render json: @json.to_json
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def reservations
    @my_reservations = current_user.reservations.where(payed: true)
    @in_date = @my_reservations.select(&:in_date?)
    @future = @my_reservations.reject(&:started?)
    @history = @my_reservations.select(&:expired?)
  end

  def hostels
    @my_hostels = current_user.hostel_registrations.where(role: 'admin')
    @my_hostels = @my_hostels.map { |h| h.hostel }.compact
  end

  def tenants
    @hostel = Hostel.find(params[:id])
    @hostel_registrations = @hostel.hostel_registrations.where(role: 'user')
    @tenants = @hostel_registrations.select(&:no_expired_reservations?).map { |r| r.user }.compact
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tDate date
    Date.strptime(date, '%d/%m/%Y')
  end

  def toCLP value
    "$#{number_with_delimiter value.to_i, delimiter: '.'}"
  end

  def sendError(model)
    key, value = model.errors.first
    trans = I18n.t "activerecord.attributes.#{model.class.name.underscore}.#{key}"
    render js: "showToastr('error', '#{trans} #{value}')"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/dashboard/_my_hostel.html.erb
<div class="card">
  <div class="row no-gutters">
    <div class="col-auto">
      <%= image_tag my_hostel.principal_image.variant(resize: "200x150!") %>
    </div>
    <div class="col">
      <div class="card-block px-2">
        <div class="separator-1"></div>
        <h4 class="card-title"><%= my_hostel.name %></h4>
        <div class="card-body">
          <%= link_to dashboard_tenants_path(my_hostel), class: "btn btn-dark btn-sm" do %>
          <i class="fas fa-users"></i> Lista de inquilinos
          <% end %>
          <%= link_to "Modificar", edit_hostel_path(my_hostel), class: "btn btn-primary btn-sm" %>
          <%= link_to "Administrar caracteristicas", hostel_hostel_features_path(my_hostel), class: "btn btn-info btn-sm" %>
          <%= link_to "Administrar habitaciones", hostel_room_types_path(my_hostel), class: "btn btn-info btn-sm" %>
          <%= link_to "Eliminar", my_hostel, method: :delete, class: "btn btn-danger btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="separator-2"></div>

app/views/dashboard/_my_reservation.html.erb
<div class="card">
  <div class="row no-gutters">
    <div class="col-auto">
      <%= image_tag my_reservation.hostel.principal_image.variant(resize: "200x150!") %>
    </div>
    <div class="col">
      <div class="card-block px-2">
        <div class="separator-1"></div>
        <h4 class="card-title">
          <%= link_to my_reservation.hostel.name,
                      hostel_path(my_reservation.hostel) %>
          <%= link_to 'Ver detalles',
                      reservation_path(my_reservation),
                      class:'btn btn-primary',
                      style:'margin-left:10px' %>
        </h4>
        <div class="card-body">
          <h6>
            <i class="far fa-calendar-alt"></i>
            Fechas:
            <%= my_reservation.f_starting_date %> -
            <%= my_reservation.f_ending_date %>
          </h6>
          <% if type == 'in_date' %>
            <h6>Días restantes: <%= my_reservation.days_left %></h6>
          <% end %>
          <% if type == 'future' %>
            <h6>Faltan <%= my_reservation.days_remaining %> días</h6>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="separator-2"></div>

app/views/dashboard/hostels.html.erb
<%= render 'layouts/container_base', title:'Mis hostales registrados' do %>
<div class="col">
  <div class="card">
    <div class="card-body">
      <%= link_to new_hostel_path, class: "btn btn-primary btn-sm" do %>
        <i class="fas fa-plus"></i> Registrar un hostal
      <% end %>
    </div>
  </div>
  <div class="separator-2"></div>
  <%= render partial: 'my_hostel', collection: @my_hostels %>
</div>
<% end %>

app/views/dashboard/reservations.html.erb
<%= render 'layouts/container_base', title:'Mis reservaciones' do %>
<div class="container-fluid">
  <div class="row border-top border-bottom">
    <div class="col">
      <div class="separator-1"></div>
      <h3>Reservaciones activas</h3>
      <%= render partial: 'my_reservation',
                 collection: @in_date,
                 as: 'my_reservation',
                 locals:{type:'in_date'} %>
    </div>
    <div class="col border-left">
      <div class="separator-1"></div>
      <h3>Reservaciones futuras</h3>
      <%= render partial: 'my_reservation',
                 collection: @future,
                 as: 'my_reservation',
                 locals:{type:'future'} %>
    </div>
  </div>
  <div class="separator-1"></div>
  <div class="row">
    <div class="col">
      <h3>Historial</h3>
      <%= render partial: 'my_reservation',
                 collection: @history,
                 as: 'my_reservation',
                 locals:{type:'history'} %>
    </div>
  </div>
</div>
<% end %>

app/views/dashboard/tenants.html.erb
<%= render 'layouts/container_base', title:'Listado de inquilinos' do %>
<div class="col-12">
  <div class="media">
    <%= image_tag @hostel.principal_image.variant(resize: "350x300!"), class:'align-self-start mr-3' %>
    <div class="media-body">
      <h5 class="mt-0">
        <% if @tenants.count.zero? %>
          <div class="card">
            <div class="card-body">
              No hay inquilinos activos en este hostal.
            </div>
          </div>
        <% end %>
        <% @tenants.each do |tenant| %>
          <div class="card">
            <div class="card-header">
              <i class="fas fa-user"></i> <b><%= tenant.full_name %></b>
            </div>
            <div class="card-body">
              <i class="fas fa-envelope"></i> Correo de contacto: <b><%= tenant.email %></b>
              <div class="separator-2"></div>
              <div class="card">
                <div class="card-header">
                  Reservaciones
                </div>
                <div class="card">
                  <ul class="list-group list-group-flush">
                    <% tenant.hostel_registrations.find_by(hostel: @hostel, role: 'user').reservations.select(&:in_date?).each do |reservation| %>
                    <li class="list-group-item">
                      <span class="badge badge-pill badge-success">Reservación activa</span>
                      Reservación Solicitada en: <%= "#{reservation.f_starting_date} - #{reservation.f_ending_date}" %>
                      <div class="separator-1"></div>
                      <% reservation.room_types.each do |room_type| %>
                      <div class="card">
                        <div class="media">
                          <%= image_tag room_type.image.variant(resize: "100x50!"), class: 'mr-3' %>
                          <div class="media-body">
                            <h5 class="mt-0"><%= "#{room_type.name} (#{room_type.reserved_rooms.find_by(reservation: reservation).quantity} habitacion/es)" %></h5>
                          </div>
                        </div>
                      </div>
                      <% end %>
                    </li>
                    <% end %>
                    <% tenant.hostel_registrations.find_by(hostel: @hostel, role: 'user').reservations.reject(&:in_date?).each do |reservation| %>
                    <li class="list-group-item">
                      <span class="badge badge-pill badge-info">Reservación no activa</span>
                      Reservación Solicitada en: <%= "#{reservation.f_starting_date} - #{reservation.f_ending_date}" %>
                      <div class="separator-1"></div>
                      <% reservation.room_types.each do |room_type| %>
                      <div class="card">
                        <div class="media">
                          <%= image_tag room_type.image.variant(resize: "100x50!"), class: 'mr-3' %>
                          <div class="media-body">
                            <h5 class="mt-0"><%= "#{room_type.name} (#{room_type.reserved_rooms.find_by(reservation: reservation).quantity} habitacion/es)" %></h5>
                          </div>
                        </div>
                      </div>
                      <% end %>
                    </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </h5>
    </div>
  </div>
  <div class="separator-2"></div>
</div>
<% end %>