config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  post 'reservations/set_dates_and_redirect'
  post 'reservations/set_dates_room_types'
  post 'reservations/set_dates'
  get 'dashboard/hostels'
  get 'dashboard/reservations'
  get 'dashboard/hostel/:id/tenants', to: 'dashboard#tenants',
                                                   as: 'dashboard_tenants'
  root 'pages#index'
  get 'reservations/:id/pre_pay', to: 'reservations#pre_pay', as: 'reservation_pre_pay'
  get 'reservations/:id/execute', to: 'reservations#execute', as: 'reservation_execute'
  resources :reservations, only: [:index, :show, :destroy]
  resources :reserved_rooms, only: [:update, :destroy] do
    resources :reservations, only: [:update]
  end
  resources :hostels do
    resources :comments, only: [:create]
    resources :hostel_features, only: [:index, :edit, :create, :update, :destroy]
    resources :room_types, only: [:index, :new, :edit, :create, :update, :destroy] do
      post 'reservations/create'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  ## API ##
  get 'api/region/:id', to: 'api#region'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hostel_registration
  has_one :user, through: :hostel_registration
  has_one :hostel, through: :hostel_registration
  has_many :reserved_rooms, dependent: :destroy
  has_many :room_types, through: :reserved_rooms

  def actual_total
    total_counter = 0
    reserved_rooms.each { |r| total_counter += r.total }
    total_counter
  end

  def f_starting_date
    starting_date.strftime('%d/%m/%Y')
  end

  def f_ending_date
    ending_date.strftime('%d/%m/%Y')
  end

  def days
    (ending_date - starting_date).to_i
  end

  def days_left
    (ending_date - Date.current).to_i
  end

  def days_remaining
    (starting_date - Date.current).to_i
  end

  def date_hash
    {starting_date: starting_date, ending_date: ending_date}
  end

  def started?(date: Date.current)
    date >= starting_date
  end

  def expired?(date: Date.current)
    date > ending_date
  end

  def in_date?(date: Date.current)
    started?(date: date) && !expired?(date: date)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_date, only: %i[set_dates set_dates_and_redirect set_dates_room_types]

  def index
    @reservations = HostelRegistration.where(user: current_user).map { |r| r.pending_reservations }.sum
  end

  def show
    @reservation = Reservation.find(params[:id])
    @admin = @reservation.hostel.hostel_registrations.find_by(role: :admin).user
    @type = 'in_date' if @reservation.in_date?
    @type = 'future' if !@reservation.started?
    @type = 'history' if @reservation.expired?
  end

  def create
    @hostel_registration = HostelRegistration.find_by(hostel_id: params[:hostel_id], user: current_user)
    if @hostel_registration.nil?
      @hostel_registration = HostelRegistration.new
      @hostel_registration.user = current_user
      @hostel_registration.hostel_id = params[:hostel_id]
      @hostel_registration.save!
      @hostel_registration.user!
    end

    @reservation = @hostel_registration.reservations.find_by(payed: false)
    if @reservation.nil?
      @reservation = Reservation.new
      @reservation.hostel_registration = @hostel_registration
      @reservation.starting_date = session[:starting_date]
      @reservation.ending_date = session[:ending_date]
      @reservation.payed = false
      @reservation.save!
    end

    @reserved_room = @reservation.reserved_rooms.find_by(room_type_id: params[:room_type_id])
    if @reserved_room.nil?
      @reserved_room = ReservedRoom.new
      @reserved_room.reservation = @reservation
      @reserved_room.room_type_id = params[:room_type_id]
      @reserved_room.quantity = 1
    else
      unless @reserved_room.room_type.rooms_left_in_range(@reserved_room.reservation.date_hash).zero?
        @reserved_room.quantity += 1
      end
    end
    @reserved_room.save!

    redirect_to reservations_path
  end

#-------------------------------------------------------------------------------
  def pre_pay
    @reservation = Reservation.find(params[:id])
    items = @reservation.reserved_rooms.map do |reserved_room|
      {
        name: "Arriendo habitación #{reserved_room.room_type.name}",
        sku: reserved_room.room_type.id.to_s,
        price: ((reserved_room.room_type.value_per_night) / 700).round(2).to_s,
        currency: 'USD',
        quantity: reserved_room.quantity
      }
    end
    payment = PayPal::SDK::REST::Payment.new({
      intent: 'sale',
      payer: { payment_method: 'paypal' },
      redirect_urls: {
        return_url: reservation_execute_url(@reservation),
        cancel_url: root_url
      },
      transactions: {
        item_list: { items: items },
        amount: {
          total: items.map { |i| i[:price].to_f * i[:quantity] }.sum.round(2).to_s,
          currency: 'USD'
        },
        description: 'Arriendo de hostales - Clarivic'
      }
    })
    if payment.create
      redirect_to payment.links.find { |v| v.method == 'REDIRECT' }.href
    else
      render json: payment.error
    end
  end

  def execute
    paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
    if paypal_payment.execute(payer_id: params[:PayerID])
      @reservation = Reservation.find(params[:id])
      @reservation.update(payed: true)
      redirect_to dashboard_reservations_path, notice: "Su reservación ha sido registrada ¡Muchas gracias!"
    else
      redirect_to reservations_path, notice: "No se pudo generar el cobro en PayPal."
    end
  end
#-------------------------------------------------------------------------------

  def set_dates
    respond_to do |format|
      format.js
    end
  end

  def set_dates_and_redirect
    redirect_to controller: 'hostels', action: 'index',
                            region_id: params[:region_id]
  end

  def set_dates_room_types
    @hostel = Hostel.find(params[:hostel_id])
    @room_types = @hostel.room_types
  end

  private

  def set_date
    session[:starting_date] = params[:starting_date]
    session[:ending_date] = params[:ending_date]
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_reservation.html.erb
<div class="col-12" id="reservation-<%= reservation.id %>">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%= link_to reservation.hostel.name, hostel_path(reservation.hostel) %></h3>
      <h6>
        <i class="far fa-calendar-alt"></i>
        <%= "#{reservation.starting_date} - #{reservation.ending_date} (#{reservation.days} días)" %>
      </h6>
      <h5>Habitaciones</h5>
      <%= render partial: 'reservations/reserved_room', collection: reservation.reserved_rooms %>
      <span style="font-weight:bold; margin-right:10px;">
        TOTAL: <%= toCLP (reservation.actual_total * reservation.days) %>
        <i>(Por noche: <%= toCLP (reservation.actual_total) %>)</i>
      </span>
      <%= link_to 'Pagar', reservation_pre_pay_path(reservation), class:'btn btn-primary' %>
    </div>
  </div>
</div>
<div class="separator-2"></div>

app/views/reservations/_reserved_room.html.erb
<div class="card">
      <div class="row no-gutters">
          <div class="col-auto">
            <%= image_tag reserved_room.room_type.image.variant(resize: "200x150!") %>
          </div>
          <div class="col">
              <div class="card-block px-2">
                  <div class="separator-1"></div>
                  <h4 class="card-title"><%= reserved_room.room_type.name %></h4>
                  <div class="">
                    <i class="fas fa-bed"></i>
                    Habitaciones:
                    <%= form_with(model: reserved_room,
                                  method: :put, html:{style:'display:inline-block'}) do |form| %>
                      <%= form.number_field :quantity,
                          value: reserved_room.quantity,
                          style:'width:50px;', oninput:"validity.valid||(value=1)",
                          min:1, max:reserved_room.room_type.rooms_left_in_range(reserved_room.reservation.date_hash),
                          onchange:"Rails.fire(this.form, 'submit');" %>
                    <% end %>
                    <i>(de <%= reserved_room.room_type.rooms_left_in_range(reserved_room.reservation.date_hash)%> habitacion/es disponibles)</i>
                  </div>
                  <div class="">
                    <i class="fas fa-money-bill-wave"></i>
                    Valor: <%= toCLP (reserved_room.room_type.value_per_night * reserved_room.reservation.days) %>
                    <i>(Por noche:
                    <%= toCLP reserved_room.room_type.value_per_night %>)</i>
                  </div>
                  <div class="">
                    <i class="fas fa-calculator"></i>
                    Subtotal: <%= toCLP reserved_room.total * reserved_room.reservation.days %>
                    <i>(Por noche: <%= toCLP reserved_room.total %>)</i>
                  </div>
                  <div class="separator-1"></div>
                  <%= link_to reserved_room_path(reserved_room),
                              method: :delete, class:'btn btn-primary',
                              style:'position: absolute; right: 15px; top: 15px;' do %>
                    <i class="fas fa-trash-alt"></i> Quitar
                  <% end %>
              </div>
          </div>
      </div>
</div>
<div class="separator-2"></div>

app/views/reservations/index.html.erb
<%= render 'layouts/container_base', title:'Reservaciones pendientes' do %>
  <%= render @reservations %>
<% end %>

app/views/reservations/set_dates.js.erb
if ($('#card-by-form')[0] != undefined) {
  if ($('#card-by-form').css('display') == 'none') {
    Rails.fire(document.getElementById('form-by-map'), 'submit');
  } else {
    Rails.fire(document.getElementById('form-by-form'), 'submit')
  }
}

$('#starting-date').html('<%= session[:starting_date] %>');
$('#ending-date').html('<%= session[:ending_date] %>');
$('#reservation-modal').modal('toggle');

app/views/reservations/set_dates_room_types.js.erb
if ($('#room-type-list').length) {
  $('#room-type-list').html("<%= j render partial: 'hostels/room_type', collection: @room_types %>");
}

$('#starting-date').html('<%= session[:starting_date] %>');
$('#ending-date').html('<%= session[:ending_date] %>');
$('#reservation-modal').modal('toggle');

app/views/reservations/show.html.erb
<%= render 'layouts/container_base', title:"Reservación: #{@reservation.hostel.name}" do %>
  <div class="col-12">
    <div class="media">
      <%= image_tag @reservation.hostel.principal_image.variant(resize: "350x300!"), class:'align-self-start mr-3' %>
      <div class="media-body">
        <h5 class="mt-0">
        <% if @type == 'in_date' %>
        <div class="card">
          <div class="card-body bg-success text-white">
            Su reservación se encuentra activa y esta acabará en dentro de <%= @reservation.days_left %> días.
          </div>
        </div>
        <% end %>
        <% if @type == 'future' %>
        <div class="card">
          <div class="card-body bg-info text-white">
            Su reservación aún no ha comenzado, faltan <%= @reservation.days_remaining %> días.
          </div>
        </div>
        <% end %>
        <% if @type == 'history' %>
        <div class="card">
          <div class="card-body bg-dark text-white">
            Está reservación ha finalizado.
          </div>
        </div>
        <% end %>
        </h5>
        <div class="card">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><i class="fas fa-user"></i> Nombre del administrador: <b><%= @admin.full_name %></b></li>
            <li class="list-group-item"><i class="fas fa-envelope"></i> Correo de contacto: <b><%= @admin.email %></b></li>
            <li class="list-group-item"><i class="fas fa-map-marker-alt"></i> Dirección: <b><%= @reservation.hostel.full_address %></b></li>
            <li class="list-group-item"><i class="fas fa-desktop"></i> Ir a la página del hostel: <b><%= link_to '[LINK]', hostel_path(@reservation.hostel) %></b></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="separator-2"></div>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="fas fa-map-marked-alt"></i> Mapa
      </div>
      <div class="card-body">
        <div id="hostel-map" data-lat="<%= @reservation.hostel.latitude %>" data-long="<%= @reservation.hostel.longitude %>" style="height:300px; width:100%;"></div>
      </div>
    </div>
  </div>
<% end %>