config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  post 'reservations/set_dates_and_redirect'
  post 'reservations/set_dates_room_types'
  post 'reservations/set_dates'
  get 'dashboard/hostels'
  get 'dashboard/reservations'
  get 'dashboard/hostel/:id/tenants', to: 'dashboard#tenants',
                                                   as: 'dashboard_tenants'
  root 'pages#index'
  get 'reservations/:id/pre_pay', to: 'reservations#pre_pay', as: 'reservation_pre_pay'
  get 'reservations/:id/execute', to: 'reservations#execute', as: 'reservation_execute'
  resources :reservations, only: [:index, :show, :destroy]
  resources :reserved_rooms, only: [:update, :destroy] do
    resources :reservations, only: [:update]
  end
  resources :hostels do
    resources :comments, only: [:create]
    resources :hostel_features, only: [:index, :edit, :create, :update, :destroy]
    resources :room_types, only: [:index, :new, :edit, :create, :update, :destroy] do
      post 'reservations/create'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  ## API ##
  get 'api/region/:id', to: 'api#region'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :address_number, presence: true, numericality: { only_integer: true }
  validates :principal_image, presence: true

  belongs_to :commune

  has_many :hostel_registrations, dependent: :destroy
  has_many :users, through: :hostel_registrations
  has_many :comments, through: :hostel_registrations
  has_many :hostel_features, dependent: :destroy
  has_many :room_types, dependent: :destroy

  has_one :region, through: :commune
  has_one_attached :principal_image

  def region_id
    if defined? region.id
      region.id
    else
      nil
    end
  end

  def full_address
    "Chile, #{region.full_name}, #{commune.full_name}, #{address} #{address_number}"
  end

  def value_per_night_from
    room_types.map { |e| e.value_per_night }.min.to_i
  end

  def rooms_left_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    room_types.map { |r| r.rooms_left_in_range(starting_date:starting_date, ending_date:ending_date) }.sum
  end

end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_hostel, only: [:show, :edit, :update, :destroy]
  before_action :set_regions, only: [:index, :new, :edit]

  # GET /hostels
  # GET /hostels.json
  def index
    @chile = { latitude: -31.7613365, longitude: -71.3187697 }
    @region_id = params.has_key?(:region_id) ? params[:region_id] : '-1'
    mode = params[:form_mode] || 'form'

    if mode == 'form'
      if (@region_id != "-1")
        if (params.has_key?(:commune_id)) && (params[:commune_id] != "-1")
          @hostels = Commune.find(params[:commune_id]).hostels
        else
          @hostels = Region.find(params[:region_id]).hostels
        end
      else
        @hostels = Hostel.all
      end
    elsif mode == 'map'
      @hostels = Hostel.where(id: params[:hostels_id])
    end

    @hostels = @hostels.map do |h|
      if (h.rooms_left_in_range starting_date: tDate(session[:starting_date]),
                                ending_date: tDate(session[:ending_date])).positive?
        return h
      end
    end

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # GET /hostels/1
  # GET /hostels/1.json
  def show
    @room_types = @hostel.room_types
    @can_comment = false
    if user_signed_in?
      hostel_registration = @hostel.hostel_registrations.find_by(user: current_user)
      if hostel_registration
        unless hostel_registration.reservations.select { |r| (r.payed && r.started?) }.count.zero?
          @can_comment = true
        end
      end
    end
  end

  # GET /hostels/new
  def new
    @hostel = Hostel.new
  end

  # GET /hostels/1/edit
  def edit
    @communes = @hostel.region.communes
  end

  # POST /hostels
  # POST /hostels.json
  def create
    @regions = Region.all
    @hostel = Hostel.new(hostel_params)
    if @hostel.valid?
      unless params[:hostel][:principal_image].nil?
        geocoder = Geocoder.search(@hostel.full_address)
        unless geocoder.count.zero?
          (@hostel.latitude, @hostel.longitude) = geocoder.first.coordinates
          @hostel_registration = HostelRegistration.new
          @hostel_registration.user = current_user
          @hostel_registration.hostel = @hostel
          @hostel_registration.admin!
          respond_to do |format|
            format.html { redirect_to dashboard_hostels_path, notice: 'Hostal registrado correctamente.' }
            format.json { render :show, status: :created, location: @hostel }
          end
        else
          render js: "showToastr('error', 'La dirección no es válida.')"
        end
      else
        render js: "showToastr('error', 'Falta subir una imagen.')"
      end
    else
      sendError @hostel
    end
  end

  # PATCH/PUT /hostels/1
  # PATCH/PUT /hostels/1.json
  def update
    respond_to do |format|
      if @hostel.valid?
        geocoder = Geocoder.search(@hostel.address)
        unless geocoder.count.zero?
          (@hostel.latitude, @hostel.longitude) = geocoder.first.coordinates
          @hostel.update(hostel_params)
          format.html { redirect_to dashboard_hostels_path, notice: 'El hostal ha sido actualizado.' }
          format.json { render :show, status: :ok, location: @hostel }
        else
          render js: "showToastr('error', 'La dirección no es válida.')"
        end
      else
        sendError @hostel
      end
    end
  end

  # DELETE /hostels/1
  # DELETE /hostels/1.json
  def destroy
    @hostel.hostel_registrations.destroy_all
    @hostel.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_hostels_path, notice: 'El hostal fue eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostel
      @hostel = Hostel.find(params[:id])
    end

    def set_regions
      @regions = Region.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostel_params
      params.require(:hostel).permit(:user_id, :name, :address, :address_number, :commune_id, :principal_image, :description)
    end
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/views/hostels/_form.html.erb
<%= form_with(model: hostel, multipart: true) do |form| %>
  <% if hostel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hostel.errors.count, "error") %> prohibited this hostel from being saved:</h2>

      <ul>
      <% hostel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class:'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :principal_image %>
        <%= form.file_field :principal_image, class:'form-control-file' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label 'Región' %>
        <%= form.select :region_id,
          ([['Seleccione una región', -1]] + @regions.pluck(:short_name, :id)), {},
          class:'form-control', onChange: "changeCommunes(this, '#hostel_commune_id')" %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :commune %>
        <%= form.select :commune_id,
          (defined?(@communes)).nil? ? [['Seleccione una comuna', -1]] : [['Seleccione una comuna', -1]] + @communes.pluck(:short_name, :id), {},
          class:'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class:'form-control' %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :address_number %>
        <%= form.text_field :address_number, class:'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/hostels/_hostel.html.erb
<div class="card">
      <div class="row no-gutters">
          <div class="col-auto">
            <%= image_tag hostel.principal_image.variant(resize: "200x150!") %>
          </div>
          <div class="col">
              <div class="card-block px-2">
                  <div class="separator-1"></div>
                  <h4 class="card-title"><%= hostel.name %></h4>
                  <p class="card-text block-with-text hostel-description"><%= hostel.description %></p>
                  <%= link_to 'Ver más', hostel_path(hostel),
                                        class: 'btn btn-primary btn-sm' %>
                  <span style="margin-left:10px; font-weight:bold; color:rgb(70, 70, 70);">
                    Valor por noche desde:
                    $<%= number_with_delimiter hostel.value_per_night_from, delimiter: "." %>
                  </span>
              </div>
          </div>
      </div>
      <div class="card-footer w-100 text-muted text-right">
        <%= "#{hostel.commune.short_name}, #{hostel.region.short_name}" %>
      </div>
</div>
<div class="separator-2"></div>

app/views/hostels/_index_filter.html.erb
<div class="col-4 border-left">
  <div id="card-by-form" class="card hostel-filter-search">
    <div class="card-body">
      <h4 class="card-title">Filtros</h4>
      <%= form_with url: hostels_path, method: 'get', html: { id: 'form-by-form' } do |form| %>
        <%= form.hidden_field :form_mode, value: 'form' %>
        <div class="form-group">
          <%= form.label 'Región' %>
          <%= form.select :region_id,
            ([['Cualquier región', -1]] + @regions.pluck(:short_name, :id)), {selected: @region_id},
            class:'form-control',
            onChange: "changeCommunes(this, '#commune_id'); Rails.fire(this.form, 'submit')" %>
        </div>
        <div class="form-group">
          <%= form.label 'Comuna' %>
          <%= form.select :commune_id,[['Cualquier comuna', -1]], {},
            class:'form-control',
            onChange: "Rails.fire(this.form, 'submit')" %>
        </div>
      <% end %>
      <div class="btn btn-primary"
           onclick="fadeFormMap()">
        <i class="fas fa-map-marked-alt"></i> Buscar en mapa
      </div>
    </div>
  </div>
  <div id="card-by-map" class="card hostel-filter-search">
    <div class="card-body">
      <%= form_with url: hostels_path, method: 'get', html: { id: 'form-by-map' } do |form| %>
      <%= form.hidden_field :form_mode, value: 'map' %>
      <div id="all-hostels-map"
           data-lat="<%= @chile[:latitude] %>"
           data-long="<%= @chile[:longitude] %>"
           data-zoom="3"
           style="height:300px; width:100%;">
      </div>
      <% end %>
      <br>
      <div class="btn btn-primary"
          onclick="fadeFormMap()">
        Filtrar por formulario
      </div>
    </div>
  </div>
</div>

app/views/hostels/_reservation_inputs.html.erb
<div class="form-group">
  <%= form.label 'Inicio de la reserva' %>
  <%= form.text_field :starting_date, autocomplete:'off',
                      id:"starting_date-#{name}",
                      class:'form-control datepicker',
                      value:session[:starting_date] %>
</div>
<div class="form-group">
  <%= form.label 'Fin de la reserva' %>
  <%= form.text_field :ending_date, autocomplete:'off',
                      id:"ending_date-#{name}",
                      class:'form-control based-datepicker',
                      'data-based':"starting_date-#{name}",
                      value:session[:ending_date] %>
</div>
<%= form.submit 'Cambiar fechas de reservación', class:'btn btn-primary' %>

app/views/hostels/_room_type.html.erb
<div class="col-3">
  <div class="card">
    <%= image_tag room_type.image, class:'card-img-top' %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h5><%= room_type.name %></h5>
      </li>
      <li class="list-group-item">
        <i class="fas fa-money-bill-wave"></i>
        Precio por noche:
        $<%= number_with_delimiter room_type.value_per_night.to_i,
                                             delimiter: "." %>
      </li>
      <li class="list-group-item">
        <i class="fas fa-bed"></i>
        Habitaciones disponibles:
        <%= room_type.rooms_left_in_range(starting_date: tDate(session[:starting_date]), ending_date: tDate(session[:ending_date])) %> /
        <%= room_type.number_rooms %>
      </li>
      <% if user_signed_in? %>
      <li class="list-group-item">
        <%= link_to 'Reservar',
                     hostel_room_type_reservations_create_path(@hostel, room_type),
                     method: :post, class: 'btn btn-primary' %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="separator-1"></div>
</div>

app/views/hostels/edit.html.erb
<%= render 'layouts/container_base', title:'Registrar nuevo hostal',
    paragraph:'Llene el siguiente formulario para modificar los datos del hostal.' do %>
  <div class="col">
    <%= render 'form', hostel: @hostel %>
    <div class="separator-1"></div>
    <%= link_to 'Show', @hostel %> | <%= link_to 'Back', hostels_path %>
  </div>
<% end %>

app/views/hostels/index.html.erb
<%= render 'layouts/container_base', title:'Hostales' do %>
<div class="col-7">
  <h3>Listado</h3>
  <div class="card bg-primary text-white">
    <div class="card-body">
      Se muestran los hostales que posean habitaciones disponibles
      entre <span id='starting-date'><%= session[:starting_date] %></span> y
      <span id='ending-date'><%= session[:ending_date] %></span>.
      Si quieres cambiar esto, haz
      <a onclick="$('#reservation-modal').modal()" class="text-white">click aquí</a>.
    </div>
  </div>
  <br>
  <div class="hostels-list">
    <%= render @hostels %>
  </div>
</div>
<%= render 'index_filter' %>
<%= render 'layouts/modal', id:'reservation-modal', title:'Rango de reservación' do %>
  <%= form_with url: reservations_set_dates_path do |form| %>
    <%= render 'reservation_inputs', form:form, name:'form' %>
  <% end %>
<% end %>
<% end %>

app/views/hostels/index.js.erb
$('.hostels-list').empty();
$('.hostels-list').append('<%= j render @hostels %>');

app/views/hostels/new.html.erb
<%= render 'layouts/container_base', title:'Registrar nuevo hostal',
    paragraph:'Llene el siguiente formulario para registar su hostal.' do %>
  <div class="col">
    <%= render 'form', hostel: @hostel %>
    <div class="separator-1"></div>
    <%= link_to 'Volver', dashboard_hostels_path %>
  </div>
<% end %>

app/views/hostels/show.html.erb
<%= render 'layouts/container_base', title:@hostel.name do %>
  <div class="col-3 border-right">
    <%= image_tag @hostel.principal_image, class:'img-thumbnail' %>
    <div class="separator-1"></div>
    <div class="card">
      <div class="card-header">
        Información
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= @hostel.description %>
        </li>
      </ul>
    </div>
    <div class="card">
      <div class="card-body">
        <div id="hostel-map" data-lat="<%= @hostel.latitude %>" data-long="<%= @hostel.longitude %>" style="height:300px; width:100%;"></div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <i class="fas fa-map-marker-alt"></i> <%= @hostel.full_address %>
      </div>
    </div>
  </div>
  <div class="col">
    <div id="carousel-features" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @hostel.hostel_features.each_with_index do |hostel_feature, index| %>
        <div class="carousel-item <%= "#{"active" if index == 0}" %> ">
          <%= image_tag hostel_feature.image.variant(resize: "1024x300!"), class:"d-block w-100" %>
          <div class="carousel-caption" style="background-color: rgba(0, 0, 0, 0.7)">
            <h5><%= hostel_feature.title %></h5>
            <p><%= hostel_feature.description %></p>
          </div>
        </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-features" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-features" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class="separator-2"></div>
    <div class="card">
      <div class="card-header">
        Habitaciones
      </div>
      <div class="card-body">
        <div class="card bg-primary text-white">
          <div class="card-body">
            El número de habitaciones disponibles es respecto a las fechas
            entre <span id='starting-date'><%= session[:starting_date] %></span> y
            <span id='ending-date'><%= session[:ending_date] %></span>.
            Si quieres cambiar esto, haz
            <a onclick="$('#reservation-modal').modal()" class="text-white">click aquí</a>.
          </div>
        </div>
        <br>
        <div class="container-fluid">
          <div class="row" id="room-type-list">
            <%= render partial: 'hostels/room_type', collection: @room_types %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        Comentarios
      </div>
      <div class="card-body">
        <% if @can_comment %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> Añadir comentario: </h5>
            <%= form_with url: hostel_comments_path(@hostel), method: :post do |form| %>
              <%= form.text_area :message, class: 'form-control', required: true %>
              <div class="separator-1"></div>
              <%= form.submit 'Enviar comentario', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
        <% end %>
        <div class="separator-2"></div>
        <% @hostel.comments.order('created_at DESC').each do |comment| %>
        <div class="card">
          <div class="card-body">
            <div class="toast" style="background-color:white" aria-live="assertive" aria-atomic="true">
              <div class="toast-header">
                <strong class="mr-auto">
                  <%= comment.user.full_name %>
                </strong>
                <small><%= comment.created_at.strftime('%d/%m/%Y %H:%M:%S') %></small>
              </div>
              <div class="toast-body">
                <div class="separator-1"></div>
                <%= comment.message %>
                <div class="separator-1"></div>
              </div>
            </div>
          </div>
        </div>
          <div class="separator-1"></div>
        <% end %>
        <div class="separator-4"></div>
      </div>
    </div>
  </div>
<% end %>
<%= render 'layouts/modal', id:'reservation-modal', title:'Rango de reservación' do %>
  <%= form_with url: reservations_set_dates_room_types_path do |form| %>
    <%= form.hidden_field :hostel_id, value: @hostel.id %>
    <%= render 'reservation_inputs', form:form, name:'form' %>
  <% end %>
<% end %>