config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  post 'reservations/set_dates_and_redirect'
  post 'reservations/set_dates_room_types'
  post 'reservations/set_dates'
  get 'dashboard/hostels'
  get 'dashboard/reservations'
  get 'dashboard/hostel/:id/tenants', to: 'dashboard#tenants',
                                                   as: 'dashboard_tenants'
  root 'pages#index'
  get 'reservations/:id/pre_pay', to: 'reservations#pre_pay', as: 'reservation_pre_pay'
  get 'reservations/:id/execute', to: 'reservations#execute', as: 'reservation_execute'
  resources :reservations, only: [:index, :show, :destroy]
  resources :reserved_rooms, only: [:update, :destroy] do
    resources :reservations, only: [:update]
  end
  resources :hostels do
    resources :comments, only: [:create]
    resources :hostel_features, only: [:index, :edit, :create, :update, :destroy]
    resources :room_types, only: [:index, :new, :edit, :create, :update, :destroy] do
      post 'reservations/create'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  ## API ##
  get 'api/region/:id', to: 'api#region'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true

  belongs_to :hostel_registration
  has_one :hostel, through: :hostel_registration
  has_one :user, through: :hostel_registration
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :hostels
end

app/models/hostel.rb
class Hostel < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :address_number, presence: true, numericality: { only_integer: true }
  validates :principal_image, presence: true

  belongs_to :commune

  has_many :hostel_registrations, dependent: :destroy
  has_many :users, through: :hostel_registrations
  has_many :comments, through: :hostel_registrations
  has_many :hostel_features, dependent: :destroy
  has_many :room_types, dependent: :destroy

  has_one :region, through: :commune
  has_one_attached :principal_image

  def region_id
    if defined? region.id
      region.id
    else
      nil
    end
  end

  def full_address
    "Chile, #{region.full_name}, #{commune.full_name}, #{address} #{address_number}"
  end

  def value_per_night_from
    room_types.map { |e| e.value_per_night }.min.to_i
  end

  def rooms_left_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    room_types.map { |r| r.rooms_left_in_range(starting_date:starting_date, ending_date:ending_date) }.sum
  end

end

app/models/hostel_feature.rb
class HostelFeature < ApplicationRecord
  validates :title, presence: true
  belongs_to :hostel

  has_one_attached :image
end

app/models/hostel_registration.rb
class HostelRegistration < ApplicationRecord
  belongs_to :user
  belongs_to :hostel
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy

  enum role: %i[user admin]

  def pending_reservations
    reservations.where(payed: false)
  end

  def has_active_reservations?
    reservations.select { |r| r.payed? && r.in_date? }.count.positive?
  end

  def no_expired_reservations?
    reservations.select { |r| r.payed? && !r.expired? }.count.positive?
  end
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :communes
  has_many :hostels, through: :communes
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hostel_registration
  has_one :user, through: :hostel_registration
  has_one :hostel, through: :hostel_registration
  has_many :reserved_rooms, dependent: :destroy
  has_many :room_types, through: :reserved_rooms

  def actual_total
    total_counter = 0
    reserved_rooms.each { |r| total_counter += r.total }
    total_counter
  end

  def f_starting_date
    starting_date.strftime('%d/%m/%Y')
  end

  def f_ending_date
    ending_date.strftime('%d/%m/%Y')
  end

  def days
    (ending_date - starting_date).to_i
  end

  def days_left
    (ending_date - Date.current).to_i
  end

  def days_remaining
    (starting_date - Date.current).to_i
  end

  def date_hash
    {starting_date: starting_date, ending_date: ending_date}
  end

  def started?(date: Date.current)
    date >= starting_date
  end

  def expired?(date: Date.current)
    date > ending_date
  end

  def in_date?(date: Date.current)
    started?(date: date) && !expired?(date: date)
  end
end

app/models/reserved_room.rb
class ReservedRoom < ApplicationRecord
  belongs_to :reservation
  belongs_to :room_type

  def total
    room_type.value_per_night * quantity
  end
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  validates :name, presence: true
  validates :number_rooms, presence: true, numericality: { only_integer: true }
  validates :value_per_night, presence: true, numericality: { only_integer: true }

  belongs_to :hostel
  has_many :reserved_rooms

  has_one_attached :image

  def occupied_rooms(date: Date.current)
    reserved_rooms.map { |r| r.reservation.in_date?(date: date) ? (r.reservation.payed ? r.quantity : 0) : 0 }.sum
  end

  def occupied_rooms_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    date_counter = starting_date
    rooms_stack = []
    while date_counter <= ending_date
      rooms_stack += [occupied_rooms(date: date_counter)]
      date_counter += 1
    end
    rooms_stack.max
  end

  def rooms_left(date: Date.current)
    number_rooms - occupied_rooms(date:date)
  end

  def rooms_left_in_range(starting_date: Date.current, ending_date: Date.current + 1)
    number_rooms - occupied_rooms_in_range(starting_date:starting_date, ending_date:ending_date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hostel_registrations
  has_many :hostels, through: :hostel_registrations
  has_many :reservations, through: :hostel_registrations

  def full_name
    "#{first_name} #{middle_name} #{first_surname} #{second_surname}"
  end

  enum gender: %i[male female other]
  enum access_level: %i[user admin]
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def region
    @region = Region.find(params[:id])
    @json = {
      region: @region,
      communes: @region.communes
    }

    render json: @json.to_json
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tDate date
    Date.strptime(date, '%d/%m/%Y')
  end

  def toCLP value
    "$#{number_with_delimiter value.to_i, delimiter: '.'}"
  end

  def sendError(model)
    key, value = model.errors.first
    trans = I18n.t "activerecord.attributes.#{model.class.name.underscore}.#{key}"
    render js: "showToastr('error', '#{trans} #{value}')"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/layouts/_container_base.html.erb
<div class="container-fluid base">
  <% if defined? title || defined? paragraph  %>
  <div class="row">
    <div class="col border-bottom header-base">
      <div class="separator-1"></div>
      <% if defined? title %>
      <h1><%= title %></h1>
      <div class="separator-2"></div>
      <% end %>
      <% if defined? paragraph %>
      <p><%= simple_format(paragraph) %></p>
      <% end %>
    </div>
  </div>
  <div class="separator-2"></div>
  <% end %>
  <div class="row">
    <%= yield %>
  </div>
  <div class="separator-3"></div>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid bg-primary">
  <footer class="footer text-light">
    Clarivic 2018
  </footer>
</div>

app/views/layouts/_modal.html.erb
<div id="<%= id %>" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"><%= yield %></div>
      <div class="separator-1"></div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Clarivic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to root_path, class:'nav-link' do %>
          <i class="fas fa-home"></i> Página inicial
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to dashboard_reservations_path, class:'dropdown-item' do %>
              <i class="far fa-eye"></i> Ver mis habitaciones reservadas
            <% end %>
            <%= link_to dashboard_hostels_path, class:'dropdown-item' do %>
              <i class="fas fa-book-open"></i> Ver mis hostales registrados
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class:'dropdown-item' do %>
              <i class="fas fa-power-off"></i> Cerrar sesión
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to reservations_path, class:'nav-link' do %>
            <i class="fas fa-shopping-cart"></i> Reservaciones pendientes
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class:'nav-link' do %>
            <i class="fas fa-key"></i> Iniciar sesión
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class:'nav-link' do %>
            <i class="fas fa-user-plus"></i> Registrarse
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clarivic</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <% if defined?(notice) && !notice.nil? %>
      <script>showToastr('success', '<%= notice %>');</script>
    <% end %>
    <% if defined?(alert) && !alert.nil? %>
      <script>showToastr('error', '<%= alert %>');</script>
    <% end %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron jumbotron-fluid principal" style="margin-bottom:0">
  <div class="container">
    <h1 class="display-4">Busca tu hostal ideal, al mejor precio</h1>
    <p class="lead">Busca entre cientos de hostales y encuentra el que mejor se adapte a tus necesidades.</p>
    <%= form_with url:reservations_set_dates_and_redirect_path, local:true, html:{id:'principal-form', class:'form-inline'} do |form| %>
      <div class="form-group">
        <%= form.select :region_id,
          ([['Cualquier región', -1]] + @regions.pluck(:short_name, :id)), {},
          class:'form-control', onChange: "changeCommunes(this, '#hostel_commune_id'
          )" %>
      </div>
      <div class="input-group datepicker-group">
        <div class="input-group-prepend">
          <span class="input-group-text">
            <i class="far fa-calendar-alt"></i>Inicio
          </span>
        </div>
        <%= form.text_field :starting_date, autocomplete:'off',
                            id:'starting_date',
                            class:'form-control datepicker' %>
      </div>
      <div class="input-group datepicker-group">
        <div class="input-group-prepend">
          <span class="input-group-text">
            <i class="far fa-calendar-alt"></i>Fin
          </span>
        </div>
        <%= form.text_field :ending_date, autocomplete:'off',
                            class:'form-control based-datepicker',
                            'data-based': 'starting_date' %>
      </div>
      <div class="form-group">
        <%= form.submit 'Búscar hosteles', class:'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>
<div class="container-fluid">
  <div class="separator-2"></div>
  <div class="row">
    <div class="col">
      <h1>¿Qué es clarivic?</h1>
    </div>
  </div>
  <div class="separator-3"></div>
  <div class="row">
    <div class="col">
      <p class="text-center">
        <i class="fas fa-hotel" style="font-size:100px"></i><br><br>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
    <div class="col">
      <p class="text-center">
        <i class="fas fa-map-marked-alt" style="font-size:100px"></i><br><br>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
    <div class="col">
      <p class="text-center">
        <i class="fab fa-cc-paypal" style="font-size:100px"></i><br><br>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
  <div class="separator-2"></div>
</div>